In [1]:
import pandas as pd

allergy_data = pd.read_csv('../Data/race_sample.csv')
display(allergy_data.head(10))
allergy_data.shape
allergy_data.dtypes

,SUBJECT_ID,BIRTH_YEAR,GENDER_FACTOR,RACE_FACTOR,ETHNICITY_FACTOR,PAYER_FACTOR,ATOPIC_MARCH_COHORT,AGE_START_YEARS,AGE_END_YEARS,SHELLFISH_ALG_START,...,CASHEW_ALG_END,ATOPIC_DERM_START,ATOPIC_DERM_END,ALLERGIC_RHINITIS_START,ALLERGIC_RHINITIS_END,ASTHMA_START,ASTHMA_END,FIRST_ASTHMARX,LAST_ASTHMARX,NUM_ASTHMARX
0,256086,2001,S0 - Male,Asian,E0 - Non-Hispanic,P0 - Non-Medicaid,False,2.913073,9.185489,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.028063,8.706366,2.0
1,48892,2006,S1 - Female,Asian,E0 - Non-Hispanic,P1 - Medicaid,False,1.982204,6.915811,NaN,...,NaN,NaN,NaN,2.499658,NaN,NaN,NaN,6.045175,6.915811,2.0
2,264558,1990,S0 - Male,Asian,E0 - Non-Hispanic,P0 - Non-Medicaid,False,10.718686,18.778919,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,70323,1997,S0 - Male,Asian,E0 - Non-Hispanic,P0 - Non-Medicaid,False,4.216290,16.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,3.824778,12.999316,9.516769,9.516769,1.0
4,31931,2007,S0 - Male,Asian,E0 - Non-Hispanic,P0 - Non-Medicaid,True,0.013689,5.965777,NaN,...,NaN,0.095825,2.01232,5.921971,NaN,3.014374,NaN,2.053388,5.921971,6.0
5,296184,2000,S1 - Female,Asian,E0 - Non-Hispanic,P0 - Non-Medicaid,False,4.580424,12.331280,NaN,...,NaN,NaN,NaN,6.422998,NaN,6.951403,NaN,6.433949,12.936345,24.0
6,301397,2005,S0 - Male,Asian,E0 - Non-Hispanic,P0 - Non-Medicaid,False,0.043806,1.883641,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,272297,1993,S1 - Female,Asian,E0 - Non-Hispanic,P1 - Medicaid,False,12.468172,17.976728,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,87279,2010,S0 - Male,Asian,E0 - Non-Hispanic,P0 - Non-Medicaid,False,0.013689,3.271732,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,276306,1994,S1 - Female,Asian,E0 - Non-Hispanic,P0 - Non-Medicaid,False,11.000684,18.781656,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

SUBJECT_ID                   int64
BIRTH_YEAR                   int64
GENDER_FACTOR               object
RACE_FACTOR                 object
ETHNICITY_FACTOR            object
PAYER_FACTOR                object
ATOPIC_MARCH_COHORT           bool
AGE_START_YEARS            float64
AGE_END_YEARS              float64
SHELLFISH_ALG_START        float64
SHELLFISH_ALG_END          float64
FISH_ALG_START             float64
FISH_ALG_END               float64
MILK_ALG_START             float64
MILK_ALG_END               float64
SOY_ALG_START              float64
SOY_ALG_END                float64
EGG_ALG_START              float64
EGG_ALG_END                float64
WHEAT_ALG_START            float64
WHEAT_ALG_END              float64
PEANUT_ALG_START           float64
PEANUT_ALG_END             float64
SESAME_ALG_START           float64
SESAME_ALG_END             float64
TREENUT_ALG_START          float64
TREENUT_ALG_END            float64
WALNUT_ALG_START           float64
WALNUT_ALG_END             float64
PECAN_ALG_START            float64
PECAN_ALG_END              float64
PISTACH_ALG_START          float64
PISTACH_ALG_END            float64
ALMOND_ALG_START           float64
ALMOND_ALG_END             float64
BRAZIL_ALG_START           float64
BRAZIL_ALG_END             float64
HAZELNUT_ALG_START         float64
HAZELNUT_ALG_END           float64
CASHEW_ALG_START           float64
CASHEW_ALG_END             float64
ATOPIC_DERM_START          float64
ATOPIC_DERM_END            float64
ALLERGIC_RHINITIS_START    float64
ALLERGIC_RHINITIS_END      float64
ASTHMA_START               float64
ASTHMA_END                 float64
FIRST_ASTHMARX             float64
LAST_ASTHMARX              float64
NUM_ASTHMARX               float64
dtype: object

In [2]:
# 異常値を含まないデータを抽出する
mean = allergy_data['SHELLFISH_ALG_START'].mean()
std = allergy_data['SHELLFISH_ALG_START'].std()
threshold = mean + 3 * std
outliers = allergy_data[allergy_data['SHELLFISH_ALG_START'] > threshold]
shellfish = allergy_data[allergy_data['SHELLFISH_ALG_START'] <= threshold]

In [5]:
# それぞれのアレルゲンの発症年齢を出す
# NAを削除
shellfish = allergy_data.dropna(subset=['SHELLFISH_ALG_START'])
# shellfish = shellfish.loc[:, ['SHELLFISH_ALG_START']]
# shellfish.to_csv('../Data/shellfish.csv', mode='w', index=False)
unique_list = shellfish["SHELLFISH_ALG_START"].unique()
print("一意の「shellfish」リスト\n", unique_list)

# shellfish['SHELLFISH_ALG_START'].astype(int)
# shellfish['SHELLFISH_ALG_START'] = shellfish['SHELLFISH_ALG_START'].replace('nan','NA')
# shellfish = shellfish.dropna()
# unique_list = allergy_data["SHELLFISH_ALG_START"].unique()
# print("一意の「shellfish」リスト\n", unique_list)
# fish = allergy_data[allergy_data['FISH_ALG_START'] == True]
# milk = allergy_data[allergy_data['MILK_ALG_START'] == True]
# soy = allergy_data[allergy_data['SOY_ALG_START'] == True]
# egg = allergy_data[allergy_data['EGG_ALG_START'] == True]
# wheat = allergy_data[allergy_data['WHEAT_ALG_START'] == True]
# peanut = allergy_data[allergy_data['PEANUT_ALG_START'] == True]
# sesami = allergy_data[allergy_data['SESAME_ALG_START'] == True]
# treenut = allergy_data[allergy_data['TREENUT_ALG_START'] == True]
# wallnut = allergy_data[allergy_data['WALNUT_ALG_START'] == True]
# pecan = allergy_data[allergy_data['PECAN_ALG_START'] == True]
# psitach = allergy_data[allergy_data['PISTACH_ALG_START'] == True]
# almond = allergy_data[allergy_data['ALMOND_ALG_START'] == True]
# brazil = allergy_data[allergy_data['BRAZIL_ALG_START'] == True]
# hazel = allergy_data[allergy_data['HAZELNUT_ALG_START'] == True]
# cashew = allergy_data[allergy_data['CASHEW_ALG_START'] == True]
# shellfish.dtype

一意の「shellfish」リスト
 [ 1.5742642   2.98425736  5.77412731  1.52772074 15.90691307  7.55373032
  1.49212868  5.05407255  7.60848734  7.77275838  3.03627652  5.21013005
  0.64065708 11.42231348  3.56741958  2.01232033  3.85489391  4.
  3.09650924  7.27720739  4.03285421  1.26214921  6.4476386   8.86516085
  1.25393566  1.24572211 13.56057495  8.32032854  1.03764545  4.14510609
  2.41752225  6.47775496  1.84257358  6.65845311  1.09787817  6.1026694
  2.28884326  4.69815195  5.08145106  0.3340178  11.6605065   6.80355921
  2.66119097 10.52977413  2.76249144  3.14031485  2.05065024  6.54620123
  4.65434634 14.17932923  7.72073922 16.04106776  4.38329911  9.24572211
  5.49212868  9.87816564  2.37645448 11.33744011  1.09240246  9.59616701
 14.13826146  3.12388775  1.06776181 13.83162218 13.16084873  4.29295003
  9.76043806  9.47570157  3.79739904  5.68104038 17.59890486  4.1670089
  1.5523614   4.70910335  2.86926762  1.40999316 10.92128679 10.04791239
  0.96098563  1.33333333  1.21560575  4.78576318  3.95893224  1.25941136
  0.95824778  4.5065024   3.91786448  5.02121834  3.15674196  2.36276523
  3.14852841  1.45106092  7.02258727 10.45311431  1.10882957  1.01026694
  2.22039699  8.27652293  1.50308008  4.73648186 16.47364819  4.82409309
  1.75496235  2.57905544  4.55304586  4.80766598 11.75633128 10.54072553
  0.50376454 14.83915127  6.66666667 13.83436003  3.32375086  0.16974675
  4.21629021  3.76454483  5.2183436   6.12183436  1.11430527 12.05201916
  3.60574949  1.27857632  4.62149213  4.21081451  8.10951403  2.12457221
  1.64544832  3.57289528 12.96372348  2.68309377  4.96646133  2.88569473
  4.85420945  2.70225873  9.69472964  5.0349076   1.14989733  5.7357974
  3.01437372  5.59616701  5.16632444  4.59958932  3.20054757  5.19917864
  5.58795346 12.49555099 12.86516085  1.0294319  13.045859    1.0349076
 17.07871321 10.58179329 10.90485969  2.00136893  9.17727584 14.81451061
  9.31964408  8.04380561  1.27036277  3.00068446  0.78850103  1.47296372
  8.29021218  1.28405202  0.84599589  3.57015743  5.31416838  2.97330595
  6.76249144  5.71115674 13.50308008 13.36892539  3.55920602  0.84325804
  1.4072553   4.10403833  6.09445585  1.36892539  5.53319644  1.00479124
  3.4825462   7.70978782  1.62080767 15.4661191   8.03285421  2.32717317
  9.58521561 17.52224504  1.61533196  4.32580424 15.06639288 12.01368925
 13.61806982  8.13415469  2.02874743  4.75564682  1.34702259  1.53867214
  2.50239562  5.85626283 13.98494182  2.00684463  1.78507871  1.24845996
 14.02327173  2.89664613  7.50444901  0.3613963   2.09445585  3.06913073
  1.71663244  5.09514031  8.66255989  1.39904175  2.89117043  1.98767967
  9.96851472  6.68856947 12.29295003  3.12936345  2.00958248  3.38672142
 17.56605065  6.82272416  5.08418891 11.3100616   2.39014374  1.3798768
  1.31143053  0.74195756  1.85078713  3.79192334 12.46269678  0.90075291
  3.40314853  8.7118412   0.53114305  4.74743326  2.31348392 11.33470226
 12.84873374  1.57152635  2.02327173  9.75496235 17.79055441  1.74401095
  1.69472964  7.17590691  9.19370294  3.18959617 11.30184805  1.13894593
  3.42778919  3.41409993  3.14579055  1.9247091  11.40862423 11.31827515
  1.51403149  2.72142368  2.67488022  3.816564   10.71321013 11.77549624
 11.38398357 16.57494867 10.32443532 14.69952088  3.27173169  5.00205339
 17.29226557  1.68104038  0.56125941  5.88911704  7.19507187 17.62628337
  7.72895277  8.15879535 10.87748118 14.39014374  9.22108145  9.77412731
 14.67214237 16.49555099  2.49144422 16.34223135  5.79329227  7.04722793
 14.7926078  17.82067077  9.05954825 16.58863792 16.95550992 15.97262149
  5.97399042  1.07323751  8.74469541 18.27241615  8.90349076 15.93429158
  3.54277892  8.12046543  4.13141684  9.32511978 15.27173169  8.87611225
  9.11156742  5.5687885  10.42847365  1.41820671  6.52977413  7.8275154
 16.43531828  9.85352498 11.2991102   5.70294319  1.54414784 14.58726899
  8.50102669  4.36960986 15.90143737  8.23271732  3.1266256   6.23956194
 18.51334702 14.75154004 14.0752909  17.32511978  1.70568104 13.52224504
  5.229295   11.51540041 14.07255305 11.26625599  8.5174538   8.32854209
 18.14647502  8.43531828  8.96372348  6.91033539  1.79329227  4.26283368
 12.61327858  2.78986995 10.72689938 13.7467488  12.52566735 10.92402464
  0.89801506 12.43258042  4.09582478  2.770705   13.40999316  9.52498289
  5.75496235 14.20944559  2.4366872  10.03969884 10.16016427 11.76728268
 14.05065024  9.07049966  9.63723477 14.59548255 18.60095825 15.95893224
  3.61396304  9.97399042 13.69472964 12.66529774 14.56536619  8.08213552
 10.17111567  4.17522245  7.08008214  7.4880219  13.62354552  9.98494182
 18.20396988 12.25735797  8.07392197  8.96098563  8.95277207  1.99589322
  5.87268994 14.82546201  6.74606434 10.48049281  7.41683778  5.08966461
  4.23819302  3.63039014 14.16290212  4.08487337 12.36413415  6.70773443
  7.39767283  4.66529774 15.17316906  2.33812457 11.53182752 17.10882957
  5.16358658  2.11635866  5.41546886 14.40109514 18.56536619 11.55920602
  6.40383299  4.15058179 11.13483915  5.76591376 16.86516085  3.54004107
  9.49212868  9.48665298 10.12731006  2.19575633 15.73716632  6.17385352
  1.38261465 16.50102669 15.63312799 17.45927447 14.66940452 11.08555784
 16.66255989  7.6550308   7.84120465  4.95550992  6.26146475 15.21697467
 15.60848734  7.25530459  1.01300479  5.88637919  0.96919918 14.28884326
  8.64065708  1.06228611  2.61738535 15.89596167  4.32854209  6.71321013
 15.71800137  5.90006845  2.17659138 11.88501027  2.90485969  7.83572895
 12.80492813  1.85626283  2.68035592 15.87132101  6.32169747 10.60643395
 13.19917864  1.33880903  3.90417522 13.88090349  2.00410678 13.97399042
 12.24640657 14.4476386  18.21218344 12.92539357 12.62696783 10.15468857
  9.0403833   7.4661191   8.39425051  2.35728953  3.35660507  6.9431896
 16.87063655  0.93360712  6.52429843 11.1156742  16.02464066 12.94455852
  5.84804928  3.00889802 17.33059548  1.95208761 11.27446954 15.37029432
 16.24640657  2.11909651  4.06297057 17.12251882  2.21765914  1.65092402
  8.81861739 18.36002738 10.85284052 15.03627652 12.12320329  9.06502396
 15.21149897 17.20465435  3.24435318 12.7008898  12.55304586 17.28952772
 15.59479808  4.50376454  3.04722793  1.48117728  5.27036277  9.71663244
 13.12251882 16.3340178  11.92881588 13.11430527 17.38809035  1.85900068
 16.14236824  5.17727584  2.6146475   1.91101985 13.11978097  4.72553046
  1.32511978 18.58726899 13.47843943 12.15605749  2.94045175 12.48186174
 11.88774812 14.71868583 11.26351814  8.862423    6.45585216 13.70020534
  8.25462012 11.321013    3.66872005 18.29431896  1.29500342 13.24298426
  6.50239562  5.26762491  5.19644079  1.43189596  1.14442163 10.01232033
  4.13415469  4.68720055  7.34839151  3.97535934  3.59479808 10.01779603
  8.53661875 18.41478439  7.41409993 13.16358658  7.74264203  9.65639973
  6.04517454  9.34154689  5.82340862  4.92265572 16.37234771  5.79603012
  3.09377139 11.86310746 10.34360027 12.93634497  6.21765914 11.43326489
 10.28610541 13.86173854  4.183436    5.52772074 10.19301848  6.23134839
 16.28199863  7.06365503  5.58247775  6.80629706  8.55030801 12.07392197
  2.49418207 12.28747433  2.31074606  1.27310062 16.44900753 13.67830253]

In [7]:
# cols = allergy_data.columns.drop(['GENDER_FACTOR', 'RACE_FACTOR', 'ETHNICITY_FACTOR', 'PAYER_FACTOR', 'ATOPIC_MARCH_COHORT'])
# allergy_data[cols] = allergy_data[cols].apply(pd.to_numeric, errors='coerce', downcast='integer')

# allergy_data[['SHELLFISH_ALG_START', 'FISH_ALG_START','MILK_ALG_START', 'SOY_ALG_START',
#               'EGG_ALG_START', 'WHEAT_ALG_START','PEANUT_ALG_START', 'SESAME_ALG_START',
#               'TREENUT_ALG_START', 'WALNUT_ALG_START','PECAN_ALG_START', 'PISTACH_ALG_START',
#               'ALMOND_ALG_START', 'BRAZIL_ALG_START','HAZELNUT_ALG_START', 'CASHEW_ALG_START'
#              ]] = allergy_data[['SHELLFISH_ALG_START', 'FISH_ALG_START','MILK_ALG_START', 'SOY_ALG_START',
#               'EGG_ALG_START', 'WHEAT_ALG_START','PEANUT_ALG_START', 'SESAME_ALG_START',
#               'TREENUT_ALG_START', 'WALNUT_ALG_START','PECAN_ALG_START', 'PISTACH_ALG_START',
#               'ALMOND_ALG_START', 'BRAZIL_ALG_START','HAZELNUT_ALG_START', 'CASHEW_ALG_START'
#                ]].apply(pd.to_numeric, errors='coerce', downcast='integer')
shellfish['SHELLFISH_ALG_START'] = pd.to_numeric(shellfish['SHELLFISH_ALG_START'], errors='coerce', downcast='integer')
shellfish'SHELLFISH_ALG_START'].dtype

/var/folders/5d/b7fwtkfx04x29cf5dnldt0kw0000gn/T/ipykernel_10864/963956425.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shellfish['SHELLFISH_ALG_START'] = pd.to_numeric(shellfish['SHELLFISH_ALG_START'], errors='coerce', downcast='integer')

AttributeError: 'DataFrame' object has no attribute 'dtype'